FROM python:3.12-slim AS build
ADD . /pythonapp
WORKDIR /pythonapp
RUN pip install --prefix=/devops -r requirements.txt

FROM python:3.12-slim AS runtime
LABEL PROJECT="pythonproject"
LABEL author="devopsteam"
COPY --from=build /pythonapp /aws
COPY --from=build /devops /usr/local
WORKDIR /aws
EXPOSE 8080
CMD [ "python3","app.py" ]
